/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperLoginRouteImport } from './routes/super.login'
import { Route as SuperDashboardRouteImport } from './routes/super.dashboard'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as ProductoFarmaciaIdMedicamentoIdRouteImport } from './routes/producto.$farmaciaId.$medicamentoId'

const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperLoginRoute = SuperLoginRouteImport.update({
  id: '/super/login',
  path: '/super/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperDashboardRoute = SuperDashboardRouteImport.update({
  id: '/super/dashboard',
  path: '/super/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductoFarmaciaIdMedicamentoIdRoute =
  ProductoFarmaciaIdMedicamentoIdRouteImport.update({
    id: '/producto/$farmaciaId/$medicamentoId',
    path: '/producto/$farmaciaId/$medicamentoId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacidad': typeof PrivacidadRoute
  '/terminos': typeof TerminosRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/super/dashboard': typeof SuperDashboardRoute
  '/super/login': typeof SuperLoginRoute
  '/producto/$farmaciaId/$medicamentoId': typeof ProductoFarmaciaIdMedicamentoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacidad': typeof PrivacidadRoute
  '/terminos': typeof TerminosRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/super/dashboard': typeof SuperDashboardRoute
  '/super/login': typeof SuperLoginRoute
  '/producto/$farmaciaId/$medicamentoId': typeof ProductoFarmaciaIdMedicamentoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacidad': typeof PrivacidadRoute
  '/terminos': typeof TerminosRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/super/dashboard': typeof SuperDashboardRoute
  '/super/login': typeof SuperLoginRoute
  '/producto/$farmaciaId/$medicamentoId': typeof ProductoFarmaciaIdMedicamentoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacidad'
    | '/terminos'
    | '/admin/dashboard'
    | '/admin/login'
    | '/super/dashboard'
    | '/super/login'
    | '/producto/$farmaciaId/$medicamentoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacidad'
    | '/terminos'
    | '/admin/dashboard'
    | '/admin/login'
    | '/super/dashboard'
    | '/super/login'
    | '/producto/$farmaciaId/$medicamentoId'
  id:
    | '__root__'
    | '/'
    | '/privacidad'
    | '/terminos'
    | '/admin/dashboard'
    | '/admin/login'
    | '/super/dashboard'
    | '/super/login'
    | '/producto/$farmaciaId/$medicamentoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacidadRoute: typeof PrivacidadRoute
  TerminosRoute: typeof TerminosRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  SuperDashboardRoute: typeof SuperDashboardRoute
  SuperLoginRoute: typeof SuperLoginRoute
  ProductoFarmaciaIdMedicamentoIdRoute: typeof ProductoFarmaciaIdMedicamentoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super/login': {
      id: '/super/login'
      path: '/super/login'
      fullPath: '/super/login'
      preLoaderRoute: typeof SuperLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super/dashboard': {
      id: '/super/dashboard'
      path: '/super/dashboard'
      fullPath: '/super/dashboard'
      preLoaderRoute: typeof SuperDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producto/$farmaciaId/$medicamentoId': {
      id: '/producto/$farmaciaId/$medicamentoId'
      path: '/producto/$farmaciaId/$medicamentoId'
      fullPath: '/producto/$farmaciaId/$medicamentoId'
      preLoaderRoute: typeof ProductoFarmaciaIdMedicamentoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacidadRoute: PrivacidadRoute,
  TerminosRoute: TerminosRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  SuperDashboardRoute: SuperDashboardRoute,
  SuperLoginRoute: SuperLoginRoute,
  ProductoFarmaciaIdMedicamentoIdRoute: ProductoFarmaciaIdMedicamentoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
